# Generated by Django 2.2.1 on 2019-10-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20191003_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('在室', '不在')], max_length=30, verbose_name='user status'),
        ),
    ]
