# Generated by Django 2.2.1 on 2019-10-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20191004_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mac',
            field=models.CharField(blank=True, max_length=18, verbose_name='mac address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('0', '在室'), ('1', '不在')], max_length=30, verbose_name='user status'),
        ),
    ]
